// templates/Web/Projects/KendoReactDefault/src/components/MenuNavContainer.jsx
﻿import React from 'react';
import { Link } from 'react-router-dom';
import { Menu, MenuItem } from '@progress/kendo-react-layout';


const MenuNavContainer = (props) => {
    return (
        <Menu>
            <MenuItem text="Home" render={()=> <Link to={'/'}>Home</Link>}/>
        </Menu>
    );
}

export default MenuNavContainer;

// kendo-ui-template-wizard/templates/Web/Projects/KendoVueDefault/src/components/MenuNavContainer.vue
﻿<template>
    <Menu>
      <li>
        <router-link class="k-link k-menu-link" to="/">Home</router-link>
      </li>
    </Menu>
</template>
<script>
import '@progress/kendo-ui/js/kendo.menu';
import { Menu } from "@progress/kendo-layout-vue-wrapper";
export default {
    components: {
       Menu
    }
}
</script>
