// templates/Web/Pages/Vue.List/src/components/ListItem.vue
<template>
  <div class="col-12 mb-3 border">
    <div class="row">
      <div class="col-11">
        <p class="mt-3">{{listItem.text}}</p>
      </div>
      <div class="col-1">
        <button
          type="button"
          class="close py-2"
          data-dismiss="alert"
          aria-label="Close"
          v-on:click="$emit('onDeleteListItem', listItem)"
        >
          <div aria-hidden="true">&times;</div>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ListItem",
  props: {
    listItem: Object
  }
};
</script>

// templates/Web/Pages/Angular.List/src/app/app-shell/Param_SourceName_Kebab/list-item/list-item.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.css']
})
export class ListItemComponent implements OnInit {
  // tslint:disable-next-line
  @Input() _id: number;
  @Input() text: string;
  @Output() deleteText = new EventEmitter<number>();
  constructor() { }

  ngOnInit() {
  }

  onDeleteListItem() {
    this.deleteText.emit(this._id);
  }

}

<div class="row">
  <div class="col-11">
    <p class="mt-3">{{ text }}</p>
  </div>
  <div class="col-1">
    <button
      type="button"
      class="close py-2"
      data-dismiss="alert"
      aria-label="Close"
      (click)="onDeleteListItem()"
    >
      <div aria-hidden="true">&times;</div>
    </button>
  </div>
</div>
