// kendo-ui-template-wizard/templates/Web/_composition/KendoReact/Page.Kendo.React.AddCommandCell/src/components/myCommandCell.jsx
﻿import React from 'react';
import { GridCell } from '@progress/kendo-react-grid';

export function MyCommandCell({ edit, remove, add, update, discard, cancel, editField }) {
    return class extends GridCell {
        render() {
            const { dataItem } = this.props;
            const inEdit = dataItem[editField];
            const isNewItem = dataItem.ProductID === undefined;

            return inEdit ? (
                <td className="k-command-cell">
                    <button
                        className="k-button k-grid-save-command"
                        onClick={() => isNewItem ? add(dataItem) : update(dataItem)}
                    >
                        {isNewItem ? 'Add' : 'Update'}
                    </button>
                    <button
                        className="k-button k-grid-cancel-command"
                        onClick={() => isNewItem ? discard(dataItem) : cancel(dataItem)}
                    >
                        {isNewItem ? 'Discard' : 'Cancel'}
                    </button>
                </td>
            ) : (
                <td className="k-command-cell">
                    <button
                        className="k-primary k-button k-grid-edit-command"
                        onClick={() => edit(dataItem)}
                    >
                        Edit
                    </button>
                    <button
                        className="k-button k-grid-remove-command"
                        onClick={() =>
                            remove(dataItem)
                        }
                    >
                        Remove
                    </button>
                </td>
            );
        }
    }
};

// templates/Web/_composition/KendoVue/Page.Kendo.Vue.AddCommandCell/src/components/myCommandCell.vue
﻿<template>
    <td v-if="!dataItem['inEdit']" class="k-command-cell">
        <button
            class="k-primary k-button k-grid-edit-command"
            @click="editHandler">
            Edit
        </button>

        <button
            class="k-button k-grid-remove-command"
            @click="removeHandler">
            Remove
        </button>
    </td>
    <td v-else class="k-command-cell">
            <button
                class="k-button k-grid-save-command"
                @click="addUpdateHandler">
                {{dataItem.ProductID? 'Update' : 'Add'}}
            </button>

            <button
                class="k-button k-grid-cancel-command"
                @click="cancelDiscardHandler">
                {{dataItem.ProductID? 'Cancel' : 'Discard'}}
            </button>
        </td>
</template>
<script>

export default {
     props: {
        field: String,
        dataItem: Object,
        format: String,
        className: String,
        columnIndex: Number,
        columnsCount: Number,
        rowType: String,
        level: Number,
        expanded: Boolean,
        editor: String
    },
    setup(props, { emit }){
        const editHandler = () => {
            emit('edit', { dataItem: props.dataItem});
        };
        const removeHandler = () => {
            emit('remove', { dataItem: props.dataItem});
        };
        const addUpdateHandler = () => {
            emit('save', { dataItem: props.dataItem});
        };
        const cancelDiscardHandler = () => {
            emit('cancel', { dataItem: props.dataItem});
        };

        return {
            editHandler,
            removeHandler,
            addUpdateHandler,
            cancelDiscardHandler
        };
    }
}
</script>
