// templates/Web/Pages/Vue.List/src/components/ListForm.vue
<template>
  <form class="input-group my-3" v-on:submit.prevent="$emit('onAddListItem')">
    <input
      v-bind:value="value"
      v-on:input="$emit('input', $event.target.value)"
      type="text"
      class="form-control"
      placeholder="Add text here..."
      aria-label="Add text here..."
    >
    <button type="submit" class="btn btn-primary ml-2">Submit</button>
  </form>
</template>

<script>
export default {
  name: "ListForm",
  props: {
    value: String
  }
};
</script>

// templates/Web/Pages/Angular.List/src/app/app-shell/Param_SourceName_Kebab/list-form/list-form.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-list-form',
  templateUrl: './list-form.component.html',
  styleUrls: ['./list-form.component.css']
})
export class ListFormComponent implements OnInit {
  listForm: FormGroup;

  @Output() inputText = new EventEmitter<string>();

  constructor() { }

  ngOnInit() {
    this.listForm = new FormGroup({
      content: new FormControl('')
    });
  }

  get content() { return this.listForm.get('content'); }

  onSubmit() {
    this.inputText.emit(this.listForm.get('content').value);
    this.listForm.reset();
  }
}

<form [formGroup]="listForm" (ngSubmit)="onSubmit()" class="input-group my-3">
  <div class="col-11">
    <input
      id="content"
      class="form-control"
      placeholder="Add text here..."
      aria-label="Add text here..."
      formControlName="content"
      required
    />
    <ngb-alert type="danger" *ngIf="content.invalid && content.dirty">
      <div *ngIf="content.errors.required">
        Input must be at least 1 character long.
      </div>
    </ngb-alert>
  </div>
  <span class="input-group-btn col-1">
    <button type="submit" class="btn btn-primary" [disabled]="listForm.invalid">
      Submit
    </button>
  </span>
</form>
