// templates/Web/_composition/Vue/Page.Vue.AddWarnings/src/components/WarningMessage.vue
<template>
  <div class="alert alert-warning ml-3 warningPosition" role="alert">
    {{text}}
    <button v-on:click="$emit('onWarningClose')" class="close ml-2" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</template>

<script>
export default {
  name: "WarningMessage",
  props: {
    text: String
  }
};
</script>

<style scoped>
.warningPosition {
  position: fixed !important;
  bottom: 0;
  left: 0;
  z-index: 1030;
}
</style>

// templates/Web/_composition/AngularJS/Page.Angular.AddWarnings/src/app/shared/warning-message/warning-message.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-warning-message',
  templateUrl: './warning-message.component.html',
  styleUrls: ['./warning-message.component.css']
})
export class WarningMessageComponent implements OnInit {

  open = false;
  @Input() text = '';
  @Output() WarningMessageOpen = new EventEmitter<boolean>();

  constructor() { }

  ngOnInit() {
  }

  onWarningClose() {
    this.text = '';
    this.open = false;
    this.WarningMessageOpen.emit(this.open);
  }
}

<div
class="alert alert-warning ml-3 warningPosition"
role="alert"
>
{{text}}
<button
  (click)="onWarningClose()"
  class="close ml-2"
  aria-label="Close"
>
  <span aria-hidden="true">&times;</span>
</button>
</div>
