// templates/Web/Pages/Angular.MasterDetail/src/app/app-shell/Param_SourceName_Kebab/master-detail-sidebar-tab/master-detail-sidebar-tab.component.ts
import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';

@Component({
  selector: 'app-master-detail-sidebar-tab',
  templateUrl: './master-detail-sidebar-tab.component.html',
  styleUrls: ['./master-detail-sidebar-tab.component.css']
})
export class MasterDetailSidebarTabComponent implements OnInit {

  @Input() tabText: string;
  @Input() image: string;
  @Input() index: number;
  @Input() key: number;
  @Output() displayTabClick = new EventEmitter<number>();

  constructor() { }

  ngOnInit() {
  }

  onDisplayTabClick() {
    this.displayTabClick.emit(this.index);
  }
}

<button
  (click)="onDisplayTabClick()"
  type="button"
  class="list-group-item list-group-item-action sidebarText"
>
  <img src="{{ image }}" alt="Default Grey Avatar" class="mr-3" />
  {{ tabText }}
</button>

// templates/Web/Pages/Vue.MasterDetail/src/components/MasterDetailSideBarTab.vue
<template>
  <button
    v-on:click="$emit('onDisplayTabClick', index)"
    type="button"
    class="list-group-item list-group-item-action styles.sidebarText"
  >
    <img src="../assets/GreyAvatar.svg" alt="Default Grey Avatar" class="mr-3">
    {{tabText}}
  </button>
</template>

<script>
export default {
  name: "MasterDetailSideBarTab",
  props: {
    tabText: String,
    index: Number
  }
};
</script>

<style scoped>
.sidebarText {
  font-weight: 500;
}
</style>
