// templates/Web/Projects/KendoVueDefault/src/components/Header.vue
<template>
 <div class='container-fluid'>
            <div class="d-flex border-bottom py-2">
                <div class="d-flex">
                    <div class='project-name d-flex'>
                        <span class="mx-0 my-auto logo">
                            {{projectName}}
                        </span>
                    </div>
                </div>
                <div class='d-flex ml-auto nav'>
                    <MenuNavContainer />
                </div>
            </div>
        </div>
</template>
<script>
import MenuNavContainer from "./MenuNavContainer"

export default {
    components: {
        MenuNavContainer
    },
    props: {
        projectName: String
    }
}
</script>

// templates/Web/Projects/KendoReactDefault/src/components/Header.jsx
import React from 'react'
import MenuNavContainer from './MenuNavContainer.jsx'

export const Header = (props) => {
    return (
        <div className='container-fluid'>
            <div className="d-flex border-bottom py-2">
                <div className="d-flex">
                    <div className='project-name d-flex'>
                        <span className="mx-0 my-auto logo">
                            {props.projectName}
                        </span>
                    </div>
                </div>
                <div className='d-flex ml-auto nav'>
                    <MenuNavContainer />
                </div>
            </div>
        </div>
    )
}
