// templates/Web/Pages/KendoReact.Form/src/components/Param_SourceName_Pascal.jsx
﻿import React, { useState } from 'react';
import { Input, Checkbox } from '@progress/kendo-react-inputs';
import { DatePicker } from '@progress/kendo-react-dateinputs';
import { Form, Field } from '@progress/kendo-react-form';
import { Dialog, DialogActionsBar } from '@progress/kendo-react-dialogs';
import FormContainer from './FormContainer';

const emailRegex = new RegExp(/\S+@\S+\.\S+/);
const emailValidator = (value) => (emailRegex.test(value) ? "" : "Please enter a valid email.");

const EmailInput = (fieldRenderProps) => {
    const { validationMessage, visited, ...others } = fieldRenderProps;
    return (
        <div>
            <Input {...others} />
            {
                visited && validationMessage &&
                (<div className={"k-required"}>{validationMessage}</div>)
            }
        </div>
    );
};

const Param_SourceName_Pascal = (props) => {
    const initialForm = {
        firstName: '',
        lastName: '',
        dateOfBirth: new Date(),
        email: '',
        company: '',
        userName: '',
        password: '',
        twoFactor: false
    };
    const [showDialog, setShowDialog] = useState(false)

    const toggleDialog = () => {
        setShowDialog(!showDialog);
    }

    const handleSubmit = () => {
        setShowDialog(!showDialog);
    }

    return (
        <div className="container-fluid">
            {showDialog && <Dialog onClose={toggleDialog}>
                <p style={{ margin: "25px", textAlign: "center" }}>The form is successfully submitted!</p>
                <DialogActionsBar>
                    <button className="k-button" onClick={toggleDialog}>OK</button>
                </DialogActionsBar>
            </Dialog>}
            <div className='row my-4'>
                <FormContainer>
                    <Form
                        initialValues={initialForm}
                        onSubmit={handleSubmit}
                        render={(formRenderProps) => (
                            <form onSubmit={formRenderProps.onSubmit} className={'k-form'}>
                                <fieldset>
                                    <legend>User Details</legend>
                                    <div>
                                        <Field name={'firstName'} component={Input} label={'First name'} />
                                    </div>
                                    <div>
                                        <Field name={'lastName'} component={Input} label={'Last name'} />
                                    </div>
                                    <div style={{ marginTop: "1rem" }}>
                                        <Field name={'dateOfBirth'} component={DatePicker} label={'Date of Birth'} />
                                    </div>
                                    <div>
                                        <Field name={"email"} type={"email"} component={EmailInput} label={"Email"} validator={emailValidator} />
                                    </div>
                                    <div>
                                        <Field name={'company'} component={Input} label={'Your Company'} />
                                    </div>
                                </fieldset>

                                <fieldset>
                                    <legend>Credentials</legend>
                                    <div>
                                        <Field name={'userName'} component={Input} label={'Username'} placeholder="Your username" />
                                    </div>
                                    <div>
                                        <Field name={'password'} component={Input} label={'Password'} placeholder="Your password" />
                                    </div>
                                    <div style={{ marginTop: "1rem" }}>
                                        <Field name={'twoFactor'} component={Checkbox} label={'Enable two-factor authentication'} />
                                    </div>
                                </fieldset>

                                <div className="text-right">
                                    <button type="button" className="k-button" onClick={formRenderProps.onFormReset}>Clear</button> &nbsp;
                                    <button type="submit" className="k-button k-primary" disabled={!formRenderProps.allowSubmit}>Submit</button>
                                </div>
                            </form>
                        )} />
                </FormContainer>
                <div className='col-12 col-lg-3 mt-3 mt-lg-0'>
                    <h3>KendoReact Forms</h3>
                    <p>KendoReact includes a wide offering of UI components that can be used to build forms, including CSS classes to easily create and structure gorgeous forms.</p>
                    <p>The required inputs get validated upon form submission and if the validation fails, the form submission is prevented. Out of the box, KendoReact delivers components which support the HTML5 form validation and also provide props for configuring a set of minimal requirements for a component to be in a valid state.</p>
                    <p>For documentation and demos of the many form-friendly components please visit their documentation (<a href="https://www.telerik.com/kendo-react-ui/components/dateinputs/?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-react-trial-dateinputs">Date Inputs</a>, <a href="https://www.telerik.com/kendo-react-ui/components/dropdowns/?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-react-trial-dropdowns">DropDowns</a>, <a href="https://www.telerik.com/kendo-react-ui/components/inputs/?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-react-trial-inputs">Inputs</a> etc).</p>
                </div>
            </div>
        </div>
    )
}

export default Param_SourceName_Pascal;

// templates/Web/Pages/KendoVue.Form/src/components/Param_SourceName_Pascal.vue
﻿<template>
  <div class="container-fluid">
            <Dialog v-if="showDialog" @close="toggleDialog">
                <p :style='{ margin: "25px", textAlign: "center" }'>The form is successfully submitted!</p>
                <DialogActionsBar>
                    <button class="k-button" @click="toggleDialog">OK</button>
                </DialogActionsBar>
            </Dialog>
            <div class='row my-4'>
                <FormContainer>
                    <form @submit="onSubmit" class='k-form'>
                        <fieldset>
                            <legend>User Details</legend>
                            <div>
                                 <label class="k-form-field">
                                    <span>First name</span>
                                    <Input :name="'firstName'" v-model="firstName"  :placeholder="'Your Name'"  />
                                </label>
                            </div>
                            <div>
                                 <label class="k-form-field">
                                    <span>Last name</span>
                                    <Input :name="'lastName'" v-model="lastName"  :placeholder="'Your Last Email'"  />
                                 </label>
                            </div>
                            <div class="k-form-field">
                                <span>Gender</span>
                                    <input type="radio" name="gender" id="female" class="k-radio">
                                    <label class="k-radio-label" for="female">Female</label>
                                    <input type="radio" name="gender" id="male" class="k-radio">
                                    <label class="k-radio-label" for="male">Male</label></div>
                            <div>
                                <div>
                                     <label class="k-form-field">
                                    <span>Email
                                        <span class="k-required">*</span>
                                    </span>
                                    <Input :name="'email'" v-model="email" :type="'email'" :placeholder="'Your Email'" />
                                     </label>
                                    <div v-if="email && validationMessage" class="k-required">{{validationMessage}}</div>
                                </div>
                            </div>
                            <div>
                                 <label class="k-form-field">
                                    <span>Your Company</span>
                                    <Input :name="'company'" v-model="company"/>
                                 </label>
                            </div>
                        </fieldset>

                        <fieldset>
                            <legend>Credentials</legend>
                            <div>
                                <label class="k-form-field">
                                    <span>Username</span>
                                    <Input :name="'userName'" :placeholder="'Your username'" v-model="userName" />
                                </label>
                            </div>
                            <div>
                                  <label class="k-form-field">
                                    <span>Password</span>
                                    <Input name="'password'" type="password" :placeholder="'Your password'" v-model="password" />
                                  </label>
                            </div>
                            <div :style='{ marginTop: "1rem" }'>
                                <label class="k-form-field">
                                    <input type="checkbox" id="twoFactor" class="k-checkbox" v-model="twoFactor" /> 
                                <label class="k-checkbox-label" for="twoFactor">Enable two-factor authentication</label></label>
                            </div>
                        </fieldset>

                        <div class="text-right">
                            <button type="button" class="k-button" @click="onFormReset">Clear</button> &nbsp;
                            <button type="submit" class="k-button k-primary">Submit</button>
                        </div>
                    </form>
                </FormContainer>
                <div class='col-12 col-lg-3 mt-3 mt-lg-0'>
                    <h3>Kendo UI for Vue Forms</h3>
                    <p>Kendo UI for Vue includes a wide offering of UI components that can be used to build forms, including CSS classes to easily create and structure gorgeous forms.</p>
                    <p>The required inputs get validated upon form submission and if the validation fails, the form submission is prevented. Out of the box, Kendo UI for Vue delivers components which support the HTML5 form validation and also provide props for configuring a set of minimal requirements for a component to be in a valid state.</p>
                    <p>For documentation and demos of the many form-friendly components please visit their documentation (<a href="https://www.telerik.com/kendo-vue-ui/components/dateinputs/?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-vue-trial-dateinputs">Date Inputs</a>, <a href="https://www.telerik.com/kendo-vue-ui/components/dropdowns/?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-vue-trial-dropdowns">DropDowns</a>, <a href="https://www.telerik.com/kendo-vue-ui/components/inputs/?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-vue-trial-inputs">Inputs</a> etc).</p>
                </div>
            </div>
        </div>
</template>
<script>
import { Input } from '@progress/kendo-vue-inputs';
import { Dialog, DialogActionsBar } from '@progress/kendo-vue-dialogs';
import FormContainer from './FormContainer';

export default {
     components: {
        Input,
        Dialog,
        DialogActionsBar,
        FormContainer
     },
     computed: {
        validationMessage: function(){
            return (this.emailRegex.test(this.email) ? "" : "Please enter a valid email.");
        }
     },
     data: function() {
        return {
            firstName: '',
            lastName: '',
            email: '',
            company: '',
            userName: '',
            password: '',
            twoFactor: true,
            showDialog: false,
            emailRegex: new RegExp(/\S+@\S+\.\S+/),
            allowSubmit:false            
        };
     },
     methods: {
         onFormReset(){
            this.firstName = '';
            this.lastName = '';
            this.email = '';
            this.company = '';
            this.userName = '';
            this.password = '';
         },
        toggleDialog() {
            this.showDialog = !this.showDialog;
        },
        handleSubmit() {
            this.showDialog = !this.showDialog;
        },
        onSubmit(){
            event.preventDefault();
            this.showDialog = true;
            setTimeout(() => { this.showDialog = false; }, 3000);
        }
     }
}
</script>
