// templates/Web/Projects/KendoReactDefault/src/components/Footer.jsx
import React from 'react';
import LinkedinIcon from './img/linkedin.svg';
import TwitterIcon from './img/twitter.svg';
import FacebookIcon from './img/facebook.svg';
import YoutubeIcon from './img/youtube.svg';

const Footer = (props) => {
    return (
        <div className="container-fluid">
            <div className='d-flex'>
                 <div>
                <div className='mb-2 links'>
                    <a href="https://www.telerik.com/purchase/license-agreement/progress-kendoreact?utm_medium=product&utm_source=vs&utm_campaign=kendo-ui-react-branding-vs-ext">License Agreement</a>
                </div>
                <div className='copyright'>
                    Copyright © 2019 Software Corporation and/or its subsidiaries or affiliates. All Rights Reserved.
                </div>
                </div>
                <div className='d-flex ml-auto'>
                    <div className="social">
                    <a href="https://www.facebook.com/KendoUI/"><img src={FacebookIcon} alt="facebook" /></a>
                    <a href="https://twitter.com/kendoreact"><img src={TwitterIcon} alt="twitter" /></a>
                    <a href="https://www.youtube.com/results?search_query=kendoreact"><img src={YoutubeIcon} alt="youtube" /></a>
                    <a href="https://www.linkedin.com/showcase/telerik/"><img src={LinkedinIcon} alt="linkedin" /></a>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Footer;

// templates/Web/Projects/KendoVueDefault/src/components/Footer.vue
<template>
 <div class="container-fluid">
            <div class='d-flex'>
                 <div>
                <div class='mb-2 links'>
                    <a href="https://www.telerik.com/purchase/license-agreement/progress-kendovue?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-vue-awareness-license-agreement">License Agreement</a>
                </div>
                <div class='copyright'>
                    Copyright © {{currentYear}} Software Corporation and/or its subsidiaries or affiliates. All Rights Reserved.
                </div>
                </div>
                <div class='d-flex ml-auto'>
                    <div class="social">
                    <a href="https://www.facebook.com/KendoUI/"><img src="../assets/images/facebook.svg" alt="facebook" /></a>
                    <a href="https://twitter.com/KendoUI"><img src="../assets/images/twitter.svg" alt="twitter" /></a>
                    <a href="https://www.youtube.com/results?search_query=kendovue"><img src="../assets/images/youtube.svg" alt="youtube" /></a>
                    <a href="https://www.linkedin.com/showcase/telerik/"><img src="../assets/images/linkedin.svg" alt="linkedin" /></a>
                    </div>
                </div>
            </div>
        </div>
</template>
<script>

export default {
     data: function() {
        return {
            currentYear: new Date().getFullYear()
        }
    }
}
</script>
