// templates/Web/Projects/KendoReactDefault/src/components/Home.jsx
import React from 'react';

const Home = (props) => {
    return (
        <div className="container mt-5">
            <div className='row'>
                <div className='col-12'>
                    <h1 className='welcome mb-0'>Welcome to KendoReact</h1>
                    <h2 className='sub-header mt-0'>Focus on the core of your application and spend less time sweating over the UI</h2>
                </div>
            </div>
            <div className='row'>
                <div className='col-12'>
                    <h1 className='get-started'>Get Started</h1>
                </div>
            </div>
            <div className='row justify-content-center'>
                <div className='col-4 text-right'>
                    <div>
                        <img className='kendoka' src='./img/kendoka.png' alt='kendoka' />
                    </div>
                </div>
                <div className='col-4 components-list'>
                    <p>
                        <img src='./img/components.png' alt='components' />
                        <a href='https://www.telerik.com/kendo-react-ui/components/'>Components</a>
                    </p>
                    <p>
                        <img src='./img/styles.png' alt='styles' />
                        <a href='https://www.telerik.com/kendo-react-ui/components/styling/'>KendoReact Themes Overview</a>
                    </p>
                    <p>
                        <img src='./img/blogs.png' alt='blogs' />
                        <a href='https://www.telerik.com/blogs/tag/react'>Blog Posts</a>
                    </p>
                </div>
            </div>
        </div>
    )
}

export default Home;

// templates/Web/Projects/KendoVueDefault/src/components/Home.vue
<template>
        <div class="container mt-5">
            <div class='row'>
                <div class='col-12'>
                    <h1 class='welcome mb-0'>Welcome to Kendo UI for Vue</h1>
                    <h2 class='sub-header mt-0'>Focus on the core of your application and spend less time sweating over the UI</h2>
                </div>
            </div>
            <div class='row'>
                <div class='col-12'>
                    <h1 class='get-started'>Get Started</h1>
                </div>
            </div>
            <div class='row justify-content-center'>
                <div class='col-6 text-right'>
                    <div class='kendoka-div'>
                        <img class='kendoka' src="../assets/images/kendoka-vue.svg" alt='kendoka' />
                    </div>
                </div>
                <div class='col-6 components-list'>
                    <p>
                    <img src="../assets/images/components.svg"  alt='components' /> 
                        <a href='https://www.telerik.com/kendo-vue-ui/components/?utm_medium=cpm&utm_source=vscode-app&utm_campaign=kendo-ui-vue-trial-docs-and-demos'>Components & Documentation</a>
                    </p>
                    <p>
                        <img src="../assets/images/styles.svg" alt='styles' />
                        <a href='https://www.telerik.com/kendo-vue-ui/styling/?utm_medium=cpm&utm_source=vscode-app&utm_campaign=kendo-ui-vue-trial-styling'>Kendo UI for Vue Themes Overview</a>
                    </p>
                    <p>
                        <img src="../assets/images/blogs.svg" alt='blogs' />
                        <a href='https://www.telerik.com/blogs/tag/vue?utm_medium=cpm&utm_source=vscode-app&utm_campaign=kendo-ui-vue-blog-vue-blogs'>Blog Posts</a>
                    </p>
                    <p>
                        <img src="../assets/images/tutorials.svg" alt='tutorials' />
                        <a href='https://www.telerik.com/support/kendo-ui-for-vue/?utm_medium=cpm&utm_source=vscode-app&utm_campaign=kendo-ui-vue-blog-vue-hooks-pp'>Tutorials</a>
                    </p>
                </div>
            </div>
        </div>
</template>
<script>
export default {
     data: function() {
        return {
            publicPath: process.env.BASE_URL
        }
    }
}
</script>
