// templates/Web/Pages/KendoVue.Grid/src/components/Param_SourceName_Pascal.vue
﻿<template>
        <div class="container-fluid">
            <div class='row my-4'>
                <div class='col-12 col-lg-9 border-right'>
                     <Grid ref="grid"
                        :style="{height: '770px'}"
                        :data-items="gridData"
                        :edit-field="'inEdit'"
                        :take="take"
                        :skip="skip"
                        :total="total"
                        @edit="edit"
                        @remove="remove"
                        @save="save"
                        @cancel="cancel"
                        @itemchange="itemChange"
                        @dataStateChange="dataStateChange"
                        :columns="columns">
                        <grid-toolbar>
                            <button title="Add new"
                                    class="k-button k-primary"
                                    @click='insert' >
                                Add new
                            </button>
                            <button v-if="hasItemsInEdit"
                                    title="Cancel current changes"
                                    class="k-button"
                                    @click="cancelChanges">
                                    Cancel current changes
                            </button>
                        </grid-toolbar>
                        <grid-norecords>
                            There is no data available custom
                        </grid-norecords>
                    </Grid>
                </div>
                <div class='col-12 col-lg-3 mt-3 mt-lg-0'>
                    <h3>Kendo UI for Vue Grid</h3>
                    <p>The Kendo UI for Vue Data Grid (Table) provides 100+ ready-to-use features covering everything from paging, sorting, filtering, editing, and grouping to row and column virtualization, export to PDF and Excel and accessibility.</p>
                    <p>For documentation and demos of all available Grid features (filtering, sorting, paging, editing etc), please visit the <a href="https://www.telerik.com/kendo-vue-ui/components/grid/?utm_medium=cpm&utm_source=vscode-app&utm_campaign=kendo-ui-Vue-trial-grid">Kendo UI for Vue Grid documentation page.</a> </p>
                </div>
            </div>
        </div>
</template>
<script>
import Vue from 'vue';
import { Grid, GridToolbar, GridNoRecords } from '@progress/kendo-vue-grid';
import { process } from '@progress/kendo-data-query';
import myCommandCell from './myCommandCell';
import { sampleProducts } from '../common/sample-products';


Vue.component('Grid', Grid);
Vue.component('grid-toolbar', GridToolbar);
Vue.component('grid-norecords', GridNoRecords);

export default {
     data: function () {
        return {
            gridData: [],
            skip: 0,
            take: 10,
            total: 4,
            updatedData: [],
            editID: null,
            columns: [
                { field: 'ProductID', editable: false, title: 'ID', width: '50px' },
                { field: 'ProductName', title: 'Name' },
                { field: 'FirstOrderedOn', editor: 'date', title: 'First Ordered', format: '{0:d}' },
                { field: 'UnitPrice', filter: 'numeric', title: 'Unit Price' },
                { field: 'UnitsInStock', title: 'Units', filter: 'numeric', width: '150px', editor: 'numeric' },
                { cell: myCommandCell, width: '180px' }
            ]
        };
    },
    computed: {
        hasItemsInEdit() {
            return this.gridData.filter(p => p.inEdit).length > 0;
        }
    },
    created: function() {
        this.updatedData = sampleProducts;
        this.getData();
    },
    methods: {
        itemChange: function (e) {
            if (e.dataItem.ProductID) {
              let index = this.gridData.findIndex(p => p.ProductID === e.dataItem.ProductID);
              let updated = Object.assign({},this.gridData[index], {[e.field]:e.value});
              this.gridData.splice(index, 1, updated);
            } else {
              Vue.set(e.dataItem, e.field, e.value);
            }
        },
        insert() {
            const dataItem = { inEdit: true };
            this.gridData.splice(0, 0, dataItem)
        },
        edit: function (e) {
            let index = this.gridData.findIndex(p => p.ProductID === e.dataItem.ProductID);
            let updated = Object.assign({},this.gridData[index], {inEdit:true});
            this.gridData.splice(index, 1, updated);
        },
        save: function(e) {
            let index = this.gridData.findIndex(p => p.ProductID === e.dataItem.ProductID);
            let item = this.gridData[index];
            let updated = Object.assign(this.update(this.gridData.slice(), item), {inEdit:undefined});
            this.gridData.splice(index, 1, updated);
            let updateDataIndex = this.updatedData.findIndex(p => p.ProductID === e.dataItem.ProductID);
            this.updatedData.splice(updateDataIndex, 1, updated);
        },
        update(data, item, remove) {
            let updated;
            let index = data.findIndex(p => item.ProductID && p.ProductID === item.ProductID);
            if (index >= 0) {
                updated = Object.assign({}, item);
                data[index] = updated;
            } else {
                let id = 1;
                this.updatedData.forEach(p => { if (p.ProductID) { id = Math.max(p.ProductID + 1, id); } });
                updated = Object.assign({}, item, { ProductID: id });
                data.unshift(updated);
                index = 0;
            }

            if (remove) {
                data = data.splice(index, 1);
            }
            return data[index];
        },
        cancel(e) {
            if (e.dataItem.ProductID) {
                let index = this.gridData.findIndex(p => p.ProductID === e.dataItem.ProductID);
                let updateDataIndex = this.updatedData.findIndex(p => p.ProductID === e.dataItem.ProductID);
                let updated = Object.assign(this.updatedData[updateDataIndex], {'inEdit': undefined});
                this.gridData.splice(index, 1, updated);
            } else {
              let index = this.gridData.findIndex(p => JSON.stringify(e.dataItem) === JSON.stringify(p));
               
              this.gridData.splice(index, 1);
            }
        },
        remove(e) {
            e.dataItem.inEdit = undefined;
            this.update(this.gridData, e.dataItem, true);
            this.update(this.updatedData, e.dataItem, true);
            this.gridData = this.gridData.slice();
        },
        cancelChanges () {
             let editedItems = this.updatedData.filter(p => p.inEdit === true);
             if(editedItems.length){
                editedItems.forEach(
                    item => {
                       Vue.set(item, 'inEdit', undefined);
                     });
             }
            this.getData();
        },
         getData: function () {
            this.gridData = process( 
              this.updatedData,
             {
               take: this.take,
               skip: this.skip, 
               sort: this.sort, 
               filter: this.filter
            }).data;
        },
        createAppState: function(dataState) {
            this.take = dataState.take;
            this.skip = dataState.skip;
            this.filter = dataState.filter;
            this.sort = dataState.sort;
            this.getData();
        },
        dataStateChange: function (event) {
            this.createAppState(event.data);
        }
    }
}
</script>

// templates/Web/Pages/KendoReact.Grid/src/components/Param_SourceName_Pascal.jsx
﻿import React, { useState } from 'react';
import { sampleProducts } from '../common/sample-products';
import { MyCommandCell } from './MyCommandCell.jsx';
import { Grid, GridColumn as Column, GridToolbar } from '@progress/kendo-react-grid';
import { process } from '@progress/kendo-data-query';

const Param_SourceName_Pascal = (props) => {
    const editField = "inEdit";
    const [data, setData] = useState(sampleProducts);
    const [dataState, setDataState ] = useState({skip: 0, take: 10 })

    const generateId = data => data.reduce((acc, current) => Math.max(acc, current.ProductID), 0) + 1;

    const removeItem = (data, item) => {
        let index = data.findIndex(p => p === item || item.ProductID && p.ProductID === item.ProductID);
        if (index >= 0) {
            data.splice(index, 1);
        }
    }


    const enterEdit = (dataItem) => {
        setData(data.map(item =>
            item.ProductID === dataItem.ProductID ?
                { ...item, inEdit: true } : item
        ));
    }

    const remove = (dataItem) => {

        const newData = [...data];
        removeItem(newData, dataItem);
        removeItem(sampleProducts, dataItem);
        setData([...newData]);
    }

    const add = (dataItem) => {
        dataItem.inEdit = undefined;
        dataItem.ProductID = generateId(sampleProducts);

        sampleProducts.unshift(dataItem);
        setData([...data])
    }

    const discard = (dataItem) => {
        const newData = [data];
        removeItem(newData, dataItem);

        setData(newData);
    }

    const update = (dataItem) => {
        const newData = [...data]
        const updatedItem = { ...dataItem, inEdit: undefined };

        updateItem(newData, updatedItem);
        updateItem(sampleProducts, updatedItem);

        setData(newData);
    }

    const cancel = (dataItem) => {
        const originalItem = sampleProducts.find(p => p.ProductID === dataItem.ProductID);
        const newData = data.map(item => item.ProductID === originalItem.ProductID ? originalItem : item);

        setData(newData);
    }

    const updateItem = (data, item) => {
        let index = data.findIndex(p => p === item || (item.ProductID && p.ProductID === item.ProductID));
        if (index >= 0) {
            data[index] = { ...item };
        }
    }

    const itemChange = (event) => {
        const newData = data.map(item =>
            item.ProductID === event.dataItem.ProductID ?
                { ...item, [event.field]: event.value } : item
        );
        setData(newData);
    }

    const addNew = () => {
        const newDataItem = { inEdit: true, Discontinued: false };
        setData([newDataItem, ...data]);
    }

    const cancelCurrentChanges = () => {
        setData([...sampleProducts]);
    }
    let CommandCell = MyCommandCell({
        edit: enterEdit,
        remove: remove,

        add: add,
        discard: discard,

        update: update,
        cancel: cancel,

        editField: editField
    });
    const hasEditedItem = data.some(p => p.inEdit);
    return (
        <div className="container-fluid">
            <div className='row my-4'>
                <div className='col-12 col-lg-9 border-right'>
                    <Grid
                        data={process(data, dataState)}
                        onItemChange={itemChange}
                        editField={editField}
                        // pageable // uncomment to enable paging
                        // sortable // uncomment to enable sorting
                        // filterable // uncomment to enable filtering
                        // onDataStateChange={(e) => setDataState(e.data)} // uncomment to enable data operations
                        // {...dataState} // uncomment to enable data operations
                    >
                        <GridToolbar>
                            <button
                                title="Add new"
                                className="k-button k-primary"
                                onClick={addNew}
                            >
                                Add new
                </button>
                            {hasEditedItem && (
                                <button
                                    title="Cancel current changes"
                                    className="k-button"
                                    onClick={cancelCurrentChanges}
                                >
                                    Cancel current changes
                    </button>
                            )}
                        </GridToolbar>
                        <Column field="ProductID" title="Id" width="50px" editable={false} />
                        <Column field="ProductName" title="Product Name" width="250px"/>
                        <Column field="UnitsInStock" title="Units" width="150px" editor="numeric" />
                        <Column field="Discontinued" title="Discontinued" editor="boolean" />
                        <Column cell={CommandCell} width="240px" />
                    </Grid>
                </div>
                <div className='col-12 col-lg-3 mt-3 mt-lg-0'>
                    <h3>KendoReact Grid</h3>
                    <p>The KendoReact Data Grid (Table) provides 100+ ready-to-use features covering everything from paging, sorting, filtering, editing, and grouping to row and column virtualization, export to PDF and Excel and accessibility.</p>
                    <p>For documentation and demos of all available Grid features (filtering, sorting, paging, editing etc), please visit the <a href="https://www.telerik.com/kendo-react-ui/components/grid/?utm_medium=cpm&utm_source=stackblitz-app&utm_campaign=kendo-ui-react-trial-grid">KendoReact Grid documentation page.</a> </p>
                </div>
            </div>
        </div>
    );
}

export default Param_SourceName_Pascal;
