// templates/Web/Projects/AngularDefault/src/app/app-shell/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css']
})
export class NavBarComponent implements OnInit {
  skipLinkPath: string;
  constructor(private location: Location) { }

  ngOnInit() {
    this.skipLinkPath = `${this.location.path()}#mainContent`;
  }
}

<div class="skipLink">
  <a [href]="skipLinkPath">Skip to Main Content</a>
</div>
<nav
  class="navbar navbar-expand-sm navbar-light border-bottom justify-content-between"
>
  <a class="navbar-brand" routerLink="/">
    wts.AngularDefault
  </a>
  <div class="navbar-nav">
  </div>
</nav>

// templates/Web/Projects/ReactDefault/src/components/NavBar/index.jsx
import React from "react";
import { Link } from "react-router-dom";
import styles from "./navbar.module.css";

//TODO Web Template Studio: Add a new link in the NavBar for your page here.
// A skip link is included as an accessibility best practice. For more information visit https://www.w3.org/WAI/WCAG21/Techniques/general/G1.
export default function NavBar() {
  return (
    <React.Fragment>
      <div className={styles.skipLink}>
        <a href="#mainContent">Skip to Main Content</a>
      </div>
      <nav className="navbar navbar-expand-sm navbar-light border-bottom justify-content-between">
        <Link className="navbar-brand" to="/">
          wts.ReactDefault
        </Link>
        <div className="navbar-nav">
        </div>
      </nav>
    </React.Fragment>
  );
}
